# Base config file which stores the default parameters which apply to all model configurations
---

# Root directory of your project; type "pwd" in the command line to find it
root_dir: "C:/Users/bsele/Documents/Programming/machine-learning/gans"

input_data: "data/input.txt"

exp_name: "development"

# Name of dataset; must be one of the names in the dataset_map dict
dataset_name: "CelebFacesA"

# Parameters for the dataset class
dataset:

  # Path to the root of the dataset
  dataset_root: "C:/Users/bsele/Documents/datasets/celeb_faces_a_50k/50k"


# Parameters relating to the training proccess
train:

  # The optimizer to use
  optimizer_name: adam

  # Optimizers for the training process
  optimizers:
    # Parameters for the Adam optimizer
    adam:
      betas: [0.5, 0.999]

  scheduler: "step_lr"

  batch_size: 32
  learning_rate: 0.0002 
  weight_decay: 0.0

  # Various epochs used during training
  epochs:
    start_epoch: 0
    epochs: 100

    # Number of epochs to checkpo7hint (save model) after; use 'null' to turn off checkpointing
    ckpt_every: 1 #10

validation:
  batch_size: 2


cpu:
  # Number of CPU proccesses to use to load and proccess data; each process will call into Dataset.__getitem__
  num_workers: 2

# GPU parameters
cuda:

  # List of GPU devices to use
  gpus: [0]

# Logging parameters
logging:

  # Number of training steps to print the losses after 
  log_train_steps: 500

  # Estimate loss every eval_iters iterations
  # eval_interval: 100

# Reproducibility information
reproducibility:
  seed: 42


