# Parameters for DCGAN 
---

gan: "dcgan"

generator:
  # Input vector size to the generator
  input_vec: 100

  # Output channel scalar; this will be elementwise multiplied by output_channel_multiplier;
  # the output channels is determined by out_channel_k*out_channel_multiplier
  out_channel_k: 64

  # Multiplier for each Conv layer in the generator to determine the number of output channels
  out_channel_multiplier: [8, 4, 2, 1] 

  # Number of channels in the output image; should be set to 3 for RGB images 
  out_image_ch: 3


